Use Docker multistage builds for reduced imagesize
ConsenSys-archive/ganache-cli-archive pull request #563
Opened 2018-08-15 09:03 UTC by thomaseizinger

This drastically reduces the size of the resulting docker image.

The image with the `multi-stage-build` tag is the new one (73MB uncompressed) whereas the other ones are downloaded from DockerHub (573MB).

![image](https://user-images.githubusercontent.com/5486389/44140587-d7bc8b24-a0bd-11e8-9007-d03d16cf771d.png)

Is there a way how I can run tests against the new image to see if it still works correctly?
I did a manual smoke test and it seems to be working fine!

2018-08-15 21:37 UTC, davidmurdoch commented
Thanks @thomaseizinger! This looks very promising! I'm not a docker guru myself, so I'll tag in @benjamincburns or @seesemichaelj to get their feedback on this.

@seesemichaelj or @benjamincburns We should probably run our tests within the docker build, which looks like it'd be simple to configure with a multi-stage build, per: https://codefresh.io/docker-tutorial/node_docker_multistage/#creatingamulti-stagedockerfilefornode.jsapplication

2018-08-15 21:46 UTC, thomaseizinger commented
Running them within the Docker is not as useful IMO because there are no
source code changes compared to outside of Docker. Integration-tests
against the HTTP API from the outside would shed light onto whether the
system behaves correctly.

On Thu, 16 Aug 2018, 07:37 David Murdoch, <notifications@github.com> wrote:

> Thanks @thomaseizinger <https://github.com/thomaseizinger>! This looks
> very promising! I'm not a docker guru myself, so I'll tag in
> @benjamincburns <https://github.com/benjamincburns> or @seesemichaelj
> <https://github.com/seesemichaelj> to get their feedback on this.
>
> @seesemichaelj <https://github.com/seesemichaelj> or @benjamincburns
> <https://github.com/benjamincburns> We should probably run our tests
> within the docker build, which looks like it'd be simple to configure with
> a multi-stage build, per:
> https://codefresh.io/docker-tutorial/node_docker_multistage/#creatingamulti-stagedockerfilefornode.jsapplication
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/trufflesuite/ganache-cli/pull/563#issuecomment-413345840>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFO3Nbzi9Jz_-bfBi4KzAi78zkMrqc-wks5uRJSBgaJpZM4V9ye4>
> .
>

2018-08-16 00:04 UTC, benjamincburns commented
I like this idea, haven't reviewed implementation, however -- I'll leave that to you @davidmurdoch!

2018-08-16 00:30 UTC, seesemichaelj commented
I actually already reviewed the implementation; this looks great! I was in the middle of testing when I discovered an issue with our latest release that I had to handle :sweat_smile: 

Looking at this now

2018-08-16 00:44 UTC, mikeseese requested changes
I tested this (with the latest develop changes), and it worked as expected.

It should be noted that during release of Docker images, that two images are built, only the second one (smaller one) will need to be published.

One requested change however: you should also copy `/src/build/cli.node.js.map` over to the `/app` folder. This is our source mapping file.

2018-08-16 03:11 UTC, thomaseizinger commented
@seesemichaelj Just incorporated the request changes!

2018-08-16 03:33 UTC, mikeseese approved these changes
LGTM! Thanks again!

2018-08-16 03:33 UTC, merged

2018-08-16 05:29 UTC, thomaseizinger commented
Thanks for merging this so quickly!

Any chance that this is backported to the v6.1.x release?

2018-08-16 05:52 UTC, seesemichaelj commented
The 7.x series was not continued past `v7.0.0-beta.0`. I'm guessing @benjamincburns changed his mind and went to 6.1.0 instead.

The current series is the 6.1.x series. This PR will go into effect in 6.1.9, 6.2.0, or 7.0.0 (whatever is the next release, more than likely 6.1.9).

Perhaps we should look into removing the `v7.0.0-beta.0` image from docker hub.

2018-08-16 06:00 UTC, thomaseizinger commented
Oh. good to know!

Are there already plans for the next release?

On Thu, 16 Aug 2018, 15:52 Mike Seese, <notifications@github.com> wrote:

> The 7.x series was not continued past v7.0.0-beta.0. I'm guessing
> @benjamincburns <https://github.com/benjamincburns> changed his mind and
> went to 6.1.0 instead.
>
> The current series is the 6.1.x series. This PR will go into effect in
> 6.1.9, 6.2.0, or 7.0.0 (whatever is the next release, more than likely
> 6.1.9).
>
> Perhaps we should look into removing the v7.0.0-beta.0 image from docker
> hub.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/trufflesuite/ganache-cli/pull/563#issuecomment-413433760>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFO3NSSDHH8WEw8bHarowAL0-YVWKDNpks5uRQiNgaJpZM4V9ye4>
> .
>

2018-08-16 06:05 UTC, seesemichaelj commented
Unfortunately no, as it's needed. We've been trying to do it regularly (seems ~2 weeks). Sorry I don't have more details!