Allows environment variables to be used as args
ConsenSys-archive/ganache-cli-archive pull request #590
Opened 2018-11-19 02:33 UTC by tbugrara

Utilizes this yargs feature (http://yargs.js.org/docs/#api-envprefix) to allow all command line arguments to be allowed to be specified via environment variables prefixed with `GANACHE_CLI` (can easily be changed).

For example, these two commands are equivalent
```javascript
ganache-cli --mnemonic sample_mnemonic

GANACHE_CLI_MNEMONIC=sample_mnemonic ganache-cli
```

The motivation for this feature spawned from my use case: I run ganache-cli's docker image as a secondary image in CircleCI so I can automate my tests. CircleCI doesn't let me use environment variables when I use the docker entrypoint command args (`docker run ganache-cli --mnemonic $MNEMONIC` doesn't work). However I am allowed to specify a dictionary of environment variables where I hope environment variables are properly interpolated.

2019-03-01 11:22 UTC, MIKE1203 approved these changes

2019-04-04 19:35 UTC, princesinha19 approved these changes

2019-04-09 19:52 UTC, davidmurdoch requested changes
Thanks for the PR, @tbugrara! Can you also add the necessary documentation to our README.MD briefly explaining how to use this feature?

2019-04-09 19:52 UTC, davidmurdoch commented on args.js
> +    .env('GANACHE_CLI')
Let's just use `GANACHE` here.

2021-01-01 18:18 UTC, kamescg commented
Just what I needed! Launching the cli from docker-compose and needed an easy way to add environment variables in a `docker-compose.yml` file.

Does this still need documentation?

2021-08-19 20:15 UTC, closed without merging