Feat/deasync startup
ConsenSys-archive/ganache-cli-archive pull request #735
Opened 2020-04-29 20:50 UTC by nicholasjpaterno

2020-04-29 21:05 UTC, davidmurdoch requested changes

2020-04-29 21:05 UTC, davidmurdoch commented on cli.js
> +  console.log(error);
What do you think about updating this to `console.error`? Hmmmm. wonder if that'd break anyone's build if they check for errors on stdout instead of stderr. :-/

2020-04-29 21:05 UTC, davidmurdoch commented on cli.js
>  process.on('uncaughtException', function(e) {
Do you think these `process.on(...` handlers should go before the listen call now? Or doesn't it not matter since it's synchronous-ish now?

2020-04-29 21:05 UTC, davidmurdoch commented on cli.js
> +var deasync = require('deasync');
<pedantic>Use double quotes here.

2020-04-30 15:16 UTC, nicholasjpaterno commented on cli.js
>  process.on('uncaughtException', function(e) {
Definitely!  I actually was thinking about that as I was trying to fall asleep.

2020-04-30 15:17 UTC, nicholasjpaterno commented on cli.js
> +  console.log(error);
That was my concern as well.

2020-05-03 21:01 UTC, davidmurdoch commented
I've updated this PR, but I'm still not confident in its stability. Might need to beta this one for a few weeks.

2020-05-04 14:51 UTC, nicholasjpaterno reviewed
LGTM

2020-05-06 14:16 UTC, davidmurdoch commented on cli.js
> +} catch (error) {
The `try`/`catch` here may cause a failure on Windows which is why I removed it in the previous commit.

2020-05-06 20:11 UTC, davidmurdoch requested changes

2020-05-06 20:11 UTC, davidmurdoch commented on README.md
> +* `"deasync"`:  `boolean` Synchronizes ganache server startup. Useful in certain scenarios - see ganache-cli issue [#733](https://github.com/trufflesuite/ganache-cli/issues/733).
Thoughts on changing to `--experimental-deasync` until we assess the viability?

2020-05-06 20:20 UTC, nicholasjpaterno commented on README.md
> +* `"deasync"`:  `boolean` Synchronizes ganache server startup. Useful in certain scenarios - see ganache-cli issue [#733](https://github.com/trufflesuite/ganache-cli/issues/733).
I wonder if it makes sense to just put experimental in the description so we dont break anything when we remove it?

2020-05-06 20:41 UTC, davidmurdoch commented on README.md
> +* `"deasync"`:  `boolean` Synchronizes ganache server startup. Useful in certain scenarios - see ganache-cli issue [#733](https://github.com/trufflesuite/ganache-cli/issues/733).
I was thinking we could always keep the `experimental` flag around as an alias.
Meh. Let's just ship it as is. :shipit:

2020-05-06 21:56 UTC, davidmurdoch approved these changes

2020-05-06 23:29 UTC, merged